/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewsIndexRouteImport } from './routes/reviews/index'
import { Route as ReviewsReviewSlugIndexRouteImport } from './routes/reviews/$reviewSlug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsReviewSlugIndexRoute = ReviewsReviewSlugIndexRouteImport.update({
  id: '/reviews/$reviewSlug/',
  path: '/reviews/$reviewSlug/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reviews': typeof ReviewsIndexRoute
  '/reviews/$reviewSlug': typeof ReviewsReviewSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reviews': typeof ReviewsIndexRoute
  '/reviews/$reviewSlug': typeof ReviewsReviewSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/reviews/$reviewSlug/': typeof ReviewsReviewSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reviews' | '/reviews/$reviewSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reviews' | '/reviews/$reviewSlug'
  id: '__root__' | '/' | '/reviews/' | '/reviews/$reviewSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
  ReviewsReviewSlugIndexRoute: typeof ReviewsReviewSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$reviewSlug/': {
      id: '/reviews/$reviewSlug/'
      path: '/reviews/$reviewSlug'
      fullPath: '/reviews/$reviewSlug'
      preLoaderRoute: typeof ReviewsReviewSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
  ReviewsReviewSlugIndexRoute: ReviewsReviewSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
