/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsIndexRouteImport } from './routes/stats/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as StatsCallbackRouteImport } from './routes/stats/callback'
import { Route as BlogReviewSlugIndexRouteImport } from './routes/blog/$reviewSlug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsCallbackRoute = StatsCallbackRouteImport.update({
  id: '/stats/callback',
  path: '/stats/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogReviewSlugIndexRoute = BlogReviewSlugIndexRouteImport.update({
  id: '/blog/$reviewSlug/',
  path: '/blog/$reviewSlug/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stats/callback': typeof StatsCallbackRoute
  '/blog': typeof BlogIndexRoute
  '/stats': typeof StatsIndexRoute
  '/blog/$reviewSlug': typeof BlogReviewSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stats/callback': typeof StatsCallbackRoute
  '/blog': typeof BlogIndexRoute
  '/stats': typeof StatsIndexRoute
  '/blog/$reviewSlug': typeof BlogReviewSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stats/callback': typeof StatsCallbackRoute
  '/blog/': typeof BlogIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/blog/$reviewSlug/': typeof BlogReviewSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stats/callback' | '/blog' | '/stats' | '/blog/$reviewSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stats/callback' | '/blog' | '/stats' | '/blog/$reviewSlug'
  id:
    | '__root__'
    | '/'
    | '/stats/callback'
    | '/blog/'
    | '/stats/'
    | '/blog/$reviewSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatsCallbackRoute: typeof StatsCallbackRoute
  BlogIndexRoute: typeof BlogIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  BlogReviewSlugIndexRoute: typeof BlogReviewSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/callback': {
      id: '/stats/callback'
      path: '/stats/callback'
      fullPath: '/stats/callback'
      preLoaderRoute: typeof StatsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$reviewSlug/': {
      id: '/blog/$reviewSlug/'
      path: '/blog/$reviewSlug'
      fullPath: '/blog/$reviewSlug'
      preLoaderRoute: typeof BlogReviewSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatsCallbackRoute: StatsCallbackRoute,
  BlogIndexRoute: BlogIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  BlogReviewSlugIndexRoute: BlogReviewSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
