/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsIndexRouteImport } from './routes/stats/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as StatsLyricalComplexityIndexRouteImport } from './routes/stats/lyrical-complexity/index'
import { Route as StatsEarwordsIndexRouteImport } from './routes/stats/earwords/index'
import { Route as BlogReviewSlugIndexRouteImport } from './routes/blog/$reviewSlug/index'
import { Route as StatsSpotifyCallbackIndexRouteImport } from './routes/stats/spotify/callback/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsLyricalComplexityIndexRoute =
  StatsLyricalComplexityIndexRouteImport.update({
    id: '/stats/lyrical-complexity/',
    path: '/stats/lyrical-complexity/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StatsEarwordsIndexRoute = StatsEarwordsIndexRouteImport.update({
  id: '/stats/earwords/',
  path: '/stats/earwords/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogReviewSlugIndexRoute = BlogReviewSlugIndexRouteImport.update({
  id: '/blog/$reviewSlug/',
  path: '/blog/$reviewSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsSpotifyCallbackIndexRoute =
  StatsSpotifyCallbackIndexRouteImport.update({
    id: '/stats/spotify/callback/',
    path: '/stats/spotify/callback/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogIndexRoute
  '/stats': typeof StatsIndexRoute
  '/blog/$reviewSlug': typeof BlogReviewSlugIndexRoute
  '/stats/earwords': typeof StatsEarwordsIndexRoute
  '/stats/lyrical-complexity': typeof StatsLyricalComplexityIndexRoute
  '/stats/spotify/callback': typeof StatsSpotifyCallbackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogIndexRoute
  '/stats': typeof StatsIndexRoute
  '/blog/$reviewSlug': typeof BlogReviewSlugIndexRoute
  '/stats/earwords': typeof StatsEarwordsIndexRoute
  '/stats/lyrical-complexity': typeof StatsLyricalComplexityIndexRoute
  '/stats/spotify/callback': typeof StatsSpotifyCallbackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/': typeof BlogIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/blog/$reviewSlug/': typeof BlogReviewSlugIndexRoute
  '/stats/earwords/': typeof StatsEarwordsIndexRoute
  '/stats/lyrical-complexity/': typeof StatsLyricalComplexityIndexRoute
  '/stats/spotify/callback/': typeof StatsSpotifyCallbackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/stats'
    | '/blog/$reviewSlug'
    | '/stats/earwords'
    | '/stats/lyrical-complexity'
    | '/stats/spotify/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/stats'
    | '/blog/$reviewSlug'
    | '/stats/earwords'
    | '/stats/lyrical-complexity'
    | '/stats/spotify/callback'
  id:
    | '__root__'
    | '/'
    | '/blog/'
    | '/stats/'
    | '/blog/$reviewSlug/'
    | '/stats/earwords/'
    | '/stats/lyrical-complexity/'
    | '/stats/spotify/callback/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  BlogReviewSlugIndexRoute: typeof BlogReviewSlugIndexRoute
  StatsEarwordsIndexRoute: typeof StatsEarwordsIndexRoute
  StatsLyricalComplexityIndexRoute: typeof StatsLyricalComplexityIndexRoute
  StatsSpotifyCallbackIndexRoute: typeof StatsSpotifyCallbackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/lyrical-complexity/': {
      id: '/stats/lyrical-complexity/'
      path: '/stats/lyrical-complexity'
      fullPath: '/stats/lyrical-complexity'
      preLoaderRoute: typeof StatsLyricalComplexityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/earwords/': {
      id: '/stats/earwords/'
      path: '/stats/earwords'
      fullPath: '/stats/earwords'
      preLoaderRoute: typeof StatsEarwordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$reviewSlug/': {
      id: '/blog/$reviewSlug/'
      path: '/blog/$reviewSlug'
      fullPath: '/blog/$reviewSlug'
      preLoaderRoute: typeof BlogReviewSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/spotify/callback/': {
      id: '/stats/spotify/callback/'
      path: '/stats/spotify/callback'
      fullPath: '/stats/spotify/callback'
      preLoaderRoute: typeof StatsSpotifyCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  BlogReviewSlugIndexRoute: BlogReviewSlugIndexRoute,
  StatsEarwordsIndexRoute: StatsEarwordsIndexRoute,
  StatsLyricalComplexityIndexRoute: StatsLyricalComplexityIndexRoute,
  StatsSpotifyCallbackIndexRoute: StatsSpotifyCallbackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
